[openai]
openai_model="gpt-3.5-turbo-1106"
#openai_model="gpt-4-0613"
function_call="auto"
timeout=45
temperature=0

[logger_level]
default_logging_level="INFO"
'vibranium.main'="INFO"
'vibraniumdome_shields.shields.transformer_shield'="INFO"
'vibraniumdome_shields.open_telemetry.open_telemetry_parser'="INFO"

[vector_db]
collection_name="data"
#vector_db_dir=tempfile.gettempdir()
embedding_model_name="text-embedding-ada-002"

[embeddings]
cache_embeddings=false

[vibraniumdome_shields]
app="server"
high_risk_threshold=0.8
low_risk_threshold=0.2
semantic_similarity.min_prompt_len=10
semantic_similarity.default_threshold=0.34
# false for sync or true for async
# execution_mode_async=true
transformer_model_name="deepset/deberta-v3-base-injection,ProtectAI/deberta-v3-base-prompt-injection"
refusal_model_name="MoritzLaurer/deberta-v3-large-zeroshot-v1"
# sensetive_info_disc_model_name="en_core_web_lg"
sensetive_info_disc_model_name="en_core_web_trf"